-- Supabase PostgreSQL schema for DMP CRM
CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(150) NOT NULL UNIQUE, phone VARCHAR(20), photo_path VARCHAR(255), password VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL DEFAULT 'counselor' CHECK (role IN ('admin','manager','counselor')), status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')), monthly_target INT DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS password_resets (id BIGSERIAL PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash CHAR(64) NOT NULL UNIQUE, expires_at TIMESTAMP NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_password_resets_expiry ON password_resets(expires_at);
CREATE TABLE IF NOT EXISTS courses (id BIGSERIAL PRIMARY KEY, name VARCHAR(150) NOT NULL, duration VARCHAR(50), fee NUMERIC(10,2) NOT NULL DEFAULT 0, description TEXT, status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active','inactive')), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS batches (id BIGSERIAL PRIMARY KEY, course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE, batch_name VARCHAR(100) NOT NULL, start_date DATE, timing VARCHAR(100), mode VARCHAR(20) DEFAULT 'offline' CHECK (mode IN ('online','offline','hybrid')), status VARCHAR(20) DEFAULT 'upcoming' CHECK (status IN ('upcoming','running','completed')));
CREATE TABLE IF NOT EXISTS leads (id BIGSERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, phone VARCHAR(20) NOT NULL, email VARCHAR(150), city VARCHAR(100), source VARCHAR(20) DEFAULT 'other' CHECK (source IN ('facebook','google','instagram','whatsapp','referral','walk-in','website','other')), course_id BIGINT REFERENCES courses(id) ON DELETE SET NULL, status VARCHAR(20) DEFAULT 'new' CHECK (status IN ('new','contacted','follow-up','interested','not-interested','converted','junk')), assigned_to BIGINT REFERENCES users(id) ON DELETE SET NULL, created_by BIGINT REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_leads_phone ON leads(phone);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);
CREATE TABLE IF NOT EXISTS lead_notes (id BIGSERIAL PRIMARY KEY, lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE, note TEXT NOT NULL, created_by BIGINT REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS follow_ups (id BIGSERIAL PRIMARY KEY, lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE, follow_up_date TIMESTAMP NOT NULL, remarks VARCHAR(255), status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending','done','missed')), created_by BIGINT REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS admissions (id BIGSERIAL PRIMARY KEY, admission_code VARCHAR(30) NOT NULL UNIQUE, lead_id BIGINT REFERENCES leads(id) ON DELETE SET NULL, student_name VARCHAR(100) NOT NULL, phone VARCHAR(20) NOT NULL, email VARCHAR(150), course_id BIGINT NOT NULL REFERENCES courses(id), batch_id BIGINT REFERENCES batches(id) ON DELETE SET NULL, counselor_id BIGINT REFERENCES users(id) ON DELETE SET NULL, admission_date DATE NOT NULL, total_fee NUMERIC(10,2) NOT NULL DEFAULT 0, discount NUMERIC(10,2) NOT NULL DEFAULT 0, status VARCHAR(20) DEFAULT 'pending-docs' CHECK (status IN ('pending-docs','confirmed','cancelled')), id_proof_path VARCHAR(255), photo_path VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payments (id BIGSERIAL PRIMARY KEY, admission_id BIGINT NOT NULL REFERENCES admissions(id) ON DELETE CASCADE, receipt_no VARCHAR(30) NOT NULL UNIQUE, amount NUMERIC(10,2) NOT NULL, mode VARCHAR(20) DEFAULT 'cash' CHECK (mode IN ('cash','upi','bank-transfer','card','cheque')), payment_date DATE NOT NULL, remarks VARCHAR(255), created_by BIGINT REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS activity_logs (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE SET NULL, action VARCHAR(255) NOT NULL, ip_address VARCHAR(45), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO users (name, email, password, role, status) VALUES ('Super Admin', 'admin@dmpschool.com', '$2y$10$29GiQUfn.xkoefZB1NbU/eggSJfA/8UclXetK2X6V2CueYSTXFpti', 'admin', 'active') ON CONFLICT (email) DO NOTHING;
INSERT INTO courses (name, duration, fee, description) VALUES ('Digital Marketing Master Course', '6 Months', 45000.00, 'SEO, SEM, Social Media, Content, Analytics'), ('Performance Marketing (Meta & Google Ads)', '2 Months', 20000.00, 'Paid ads specialisation'), ('SEO Specialist Course', '2 Months', 15000.00, 'On-page, off-page, technical SEO') ON CONFLICT DO NOTHING;